Few tweaks

diff --git a/goon b/goon
--- a/goon
+++ b/goon
@@ -23,7 +23,7 @@ main() {
 	done
 
 	# Some commands don't need a machine.
-	local no_mach=(help ls list machines)
+	local no_mach=(help ls list machines new)
 	if [[ ${no_mach[(r)$argv[1]]:-} = $argv[1] ]]; then
 		(( $has_help )) && help '' $argv[1]
 		cmd-$argv[1] $argv[2,-1]
@@ -153,19 +153,36 @@ run-qemu() {
 	# but it can have multiple of the same (e.g. -device ...), so that doesn't
 	# actually work. Keep it for now; probably want something like this at some
 	# point.
-	print "run-qemu doesn't work"
-	exit 99
+	# print "run-qemu doesn't work"
+	# exit 99
 
-	local arch=$1
-	local img=$2
-	local pid=$3
-	local ssh_ip=$(resolve-host $ssh_host)
-	shift 3
+	# typeset -A extra=($argv)
+	# for k in ${(k)extra}; args[$k]=$extra[$k]
+	#for k in ${(k)args}; print -f "%-20s = %s\n" -- $k ${args[$k]}
 
-	if (( ! $+commands[qemu-system-$arch] )); then
-		print >&2 "$progname: qemu-system-$arch not in \$PATH; can't start QEMU"
-		return 1
-	fi
+	use_display=$argv[1] ; shift
+	iso=$argv[1]         ; shift
+	platform=$argv[1]    ; shift
+	version=$argv[1]     ; shift
+	ssh_port=$argv[1]    ; shift
+	memory=$argv[1]      ; shift
+	cores=$argv[1]       ; shift
+	threads=$argv[1]     ; shift
+	arch=$argv[1]        ; shift
+	cpu=($argv[1])       ; shift
+	extra=($argv)
+
+	# printf "%-20s %s\n" "use_display" $use_display
+	# printf "%-20s %s\n" "iso" $iso
+	# printf "%-20s %s\n" "version" $version
+	# printf "%-20s %s\n" "ssh_port" $ssh_port
+	# printf "%-20s %s\n" "memory" $memory
+	# printf "%-20s %s\n" "cores" $cores
+	# printf "%-20s %s\n" "threads" $threads
+	# printf "%-20s %s\n" "arch" $arch
+	# printf "%-20s %s\n" "cpu" ${(j:,:)cpu}
+
+	has-qemu $arch || return 1
 
 	mkdir -p $root/run
 	if has-pid $pid; then
@@ -173,33 +190,60 @@ run-qemu() {
 		return 0
 	fi
 
-	typeset -A args=(
-		-enable-kvm ''
-		-cpu        'host,kvm=on'
-		-smp        'cores=2,threads=1,sockets=1'
-		-m          '2G'
-		-name       "$machine"
-		-pidfile    "$pid"
-		-display    "none"
-		-device     "virtio-blk-pci,drive=SystemDisk"
-		-drive      "id=SystemDisk,if=none,file=$img,format=qcow2"
-		-device     'e1000,netdev=mynet0'
-		-netdev     "user,id=mynet0,hostfwd=tcp:$ssh_ip:$ssh_port-:22"
+	local display=(-display 'none')
+	(( $use_display )) && display=(
+		-display    'gtk,grab-on-hover=off,zoom-to-fit=off'
+		-device     'VGA,vgamem_mb=64'
+		# Prevents the mouse from being grabbed when clicking in the guest; QEMU
+		# will be able to report the mouse position without having to grab it.
+		# Also overrides PS/2 mouse emulation when activated.
+		-device     'usb-tablet,bus=input.0'
 	)
-	typeset -A extra=($argv)
-	for k in ${(k)extra}; args[$k]=$extra[$k]
 
-	#for k in ${(k)args}; print -f "%-20s = %s\n" -- $k ${args[$k]}
+	# Add installer CD if it exists
+	local install=()
+	[[ -n $iso ]] && install=(
+		-cdrom   "$iso"
+		-boot    'd'
+	)
 
-	local cmd=(qemu-system-$arch ${(kv)args})
-	$cmd
+	print "$progname: starting QEMU VM from $img:t"
+	local cmd=(qemu-system-$arch
+		-name       "$machine,process=$procname"
+		-pidfile    "$pid"
+		-enable-kvm
+		-machine    'q35,smm=off,vmport=off'
+		-rtc        'base=localtime,clock=host,driftfix=slew'
+		-m          "$memory"
+		-smp        "cores=$cores,threads=$threads,sockets=1"
+		-cpu        "host,kvm=on$( (( $#cpu )) && print ',' )${(j:,:)cpu}"
+		-device     'usb-ehci,id=input'
+		-smbios     "type=2,manufacturer=goon,product=goon,version=3.16,serial=0xDEADBEEF,location=arp242.net,asset=$machine"
 
-	#$k     =>    ${cmd[$k:q]:-}"
+		# Hard drive
+		-device     'virtio-blk-pci,drive=SystemDisk'
+		-drive      "id=SystemDisk,if=none,file=$img,format=qcow2"
 
-	#print -- $cmd
-	#print
-	#print -- $argv
-	#${cmd[@]}
+		$display
+		$install
+	)
+
+	# Seems to break networking.
+	[[ $platform != illumos ]] && cmd+=(-device 'virtio-balloon')
+
+	# Networking.
+	cmd+=(-netdev "user,id=nic,hostname=$machine,hostfwd=tcp:$ssh_ip:$ssh_port-:22")
+	if [[ $platform = illumos ]]; then
+		cmd+=(-device 'e1000,netdev=nic') # Can't get virtio to work
+	else
+		cmd+=(-device 'virtio-net,netdev=nic')
+	fi
+
+	# Add extra vars
+	cmd+=($extra)
+
+	print $cmd
+	# ${cmd[@]} &
 }
 
 # Check if the pidfile $1 exists, and (optionally) if the PID matches the
@@ -234,36 +278,50 @@ has-pid() {
 # Lookup host; zsh doesn't really expose anything for this as far as I can find,
 # so try a bunch of things. Note dig/host/nslookup/drill ignores /etc/hosts; we
 # can't use it.
+#
+# Returns 0 on success, 1 on resolve failure, or 2 if there is no facility to
+# resolve the name.
 resolve-host() {
+	setopt local_options no_err_exit pipefail
 	local host=$1
 
 	if (( $+commands[getent] )); then
 		local x=($(getent hosts $host))
+		(( $#x == 0 )) && return 1
 		print -r -- $x[1]
-	elif (( $+commands[systemd-resolve] )); then
-		# TODO
-		# systemd-resolve $host -t A             | awk '{print $4; exit}'
-		# systemd-resolve $host -t A --legend=no | awk '{print $4; exit}'
+	elif (( $+commands[resolveip] )); then  # MariaDB installs this.
+		resolveip -s arp242.net 2>/dev/null || return 1
 	elif (( $+commands[python] )); then
-		python -c "import socket; print(socket.gethostbyname('$host'))" # TODO: escape '
-	elif (( $+commands[ruby] )); then
-		ruby -rresolv -e "puts(Resolv.getaddress('$host'))" # TODO: escape '
+		python -c "import socket; print(socket.gethostbyname('$host'))" 2>/dev/null || return 1
 	elif (( $+commands[perl] )); then
-		perl -MSocket -MNet::hostent -E 'say inet_ntoa((gethost shift)->addr)' $host
+		perl -MSocket -MNet::hostent -E 'say inet_ntoa((gethost shift)->addr)' $host 2>/dev/null || return 1
+	elif (( $+commands[ruby] )); then
+		ruby -rresolv -e "puts(Resolv.getaddress('$host'))" 2>/dev/null || return 1
 	elif (( $+commands[php] )); then
-		php -r "print(gethostbyname('$host'));"  # TODO: escape '
-	elif (( $+commands[nc] )); then
-		nc -vNdw 1 $host 1 |& grep -Eo '\([0-9a-f.:]{7,}\)' | tr -d '()'
+		php -r "print(gethostbyname('$host') . \"\\n\");" || return 1
+	# There are different versions of nc with incompatible flags; disable until
+	# I figure out how to detect this. It's also slow as it takes 1s to connect,
+	# so may not be worth keeping anyway.
+	# elif (( $+commands[nc] )); then
+	# 	nc -vNdw 1 $host 1 |& grep -Eo '\([0-9a-f.:]{7,}\)' | tr -d '()'
 	elif (( $+commands[ping] )); then
-		local p=$(ping $host -q -c1 -w1 -W1) # quiet, count, timeout, linger
-		if (( $? > 0 )); then
-			print >&2 -r -- $p
-			return $?
-		fi
-		<<<$p head -n1 | grep -Eo '\([0-9a-f.:]{7,}\)' | tr -d '()'
+		local x=$(ping $host -q -c1 -w1 -W1 2>/dev/null) # quiet, count, timeout, linger
+		(( $? > 0 )) && return $?
+		print -r -- ${${x/)*/}/*\(/}
+	elif (( $+commands[systemd-resolve] )); then
+		# Do this last, as it may not work:
+		#
+		#   % systemd-resolve --legend=no -tA example.com
+		#   example.com: resolve call failed: Unit dbus-org.freedesktop.resolve1.service not found.
+		#
+		# On Debian I need to install libnss-resolve to make it work, which
+		# isn't installed by default.
+		local x=($(systemd-resolve --legend=no -tA example.com 2>/dev/null))
+		(( $#x == 0 )) && return 1
+		print -r -- $x[4]
 	else
 		print >&2 'resolve-host: no facility to get IP address from host'
-		return 1
+		return 2
 	fi
 }
 
